name: "Close stale issues and PRs"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-pr-message: "Your coursework submission has been closed because nobody has interacted with it in six weeks. You are welcome to re-open it to get more feedback."
          days-before-stale: 42
          days-before-close: 0
          days-before-issue-stale: -1
          days-before-issue-close: -1
